[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_TOOLS_INSTALL_DIR = { value = "global" }
# ESP_IDF_VERSION = "release/v4.4"
